### PR TITLE
Fix typo in howto vignette

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
there was something wonky going on with the builds on travis (seems like hao was having a similar problem in portlar?)...i cleared the caches and am restarting these builds to see if that fixes the problem

**Comment by juniperlsimonis** [comment]
ok, that looks like that fixed it! 
also note that i merged in a big update since you branched this off, so please rebase before merging in this PR, thanks!

**Comment by ethanwhite** [comment]
Why does it need to be rebased? It looks like it's going to merge fine.

**Comment by juniperlsimonis** [comment]
oh! maybe i just got confused by the codecov report...made it look like a bunch of stuff was changing for some reason.  my bad!

**Comment by ethanwhite** [comment]
That makes sense. I think CodeCov is looking at the PR itself rather than the merged PR, which can look a lot different if things have changed a bit since the branch started. Merge away if all looks good to you. If I'm missing something just let me know and I'll rebase.

**Pull request merged**
