### PR TITLE
[WIP] Forecast exclosure data

### PR DESCRIPTION
**Pull request by skmorgane**
This adds forecasts for the exclosure data to the prefab models.
Issues:
1) pevGarch doesn't run when I do portalcast(). It runs into issues while doing the forecasts on all. 
2) EDM, and JAGSRW don't run. These seem likely to be due to my install issues related to those two models (I  Need rEDM >= 0.7.4 but only 0.7.2 is on CRAN and I can't seem to install the version on Hao's repo.)
3) Test failures. There are 4 test failures:
   * test-14-prefab_models.R:257: error: jags_RW (can't call JAGS - so that's probably me not the code)
   * test-14-prefab_models.R:218: error: simplexEDM (my version of EDM is out of date, so probably me)
   * test-09-prepare_models.R:77: failure: model_template
length(temp1) not equal to 4.
1/1 mismatches
[1] 6 - 4 == 2
  * test-09-prepare_models.R:81: failure: model_template
length(temp2) not equal to 4.
1/1 mismatches
[1] 6 - 4 == 2

I'll be honest I couldn't figure out what lines 77 and 81 were even checking, so I didn't try to fix that.

What would be helpful:
1) So, having someone with JAGS and EDM check to see if those run on the treatment data and if the test failures disappear
2) Diagnosis of why pevGARCH is having problems.

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
i can run the `pevGARCH` model in `portalcast()`, and It doesn't look like there was an issue on travis either. can you take a screen cap of the errors you were getting?

**Comment by juniperlsimonis** [comment]
the only other thing i could think of is that `pevGARCH` should be run on `all_interp`, not `all`, so if you were telling it `all`, it might have been mad at that.

**Comment by juniperlsimonis** [comment]
i can execute the full `portalcasting` run with all prefab models on all three data sets locally, and it looks like everything runs fine on travis, so as long as you're square with the `pevGARCH` issue, it's good to be merged in!
thanks!

**Comment by skmorgane** [comment]
That is so interesting. I've rerun the same thing from my home computer (this time with rEDM updated and JAGS installed in case there was a strange edge case with not having them). I get the same error. However, since seems to have nothing to do with the changes in this branch, I'm going to go ahead an merge since its working on your computer. I'll open a separate issue re: pevGARCH with a screenshot of the error message.

**Comment by juniperlsimonis** [comment]
weird!

**Comment by skmorgane** [comment]
If there’s anything I’m good at it’s finding weird errors

**Comment by juniperlsimonis** [comment]
bahahaha. 

this also reminds me that i need to make it so the error messaging can pass through to the console so it doesn't just say that it failed

in the future (or now if you're still able to recreate the error on any machine), for the time being, if you can run any model that errors in `portalcasting` as its own function (like `pevGARCH(main= main)`), it should give more helpful errors at the console

**Pull request merged**
