### PR TITLE
Gaussian Process version of EDM

### PR DESCRIPTION
**Pull request by ha0ye**
Has "actual" error estimates, though fitting takes longer.

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
just checking back in on this PR, @ha0ye 
is the model and stuff ready to go in, just needing to be updated to address conflicts?

**Comment by ha0ye** [comment]
Yeah, it should be ready, I think. Maybe I was waiting on changes to `juniper_active` branch to be finalized?

**Comment by juniperlsimonis** [comment]
ok, i should be merging in #166 here in an hour or so (as long as the tests finalize), which is then probably a good time to get this in. do you have the bandwidth for that? i'm happy to help as needed, but def feel free to get this merged in if it's good to go. 
i'd say the appropriate version to use would be 0.17.0

**Comment by ha0ye** [comment]
Yeah, ping me then, and I can get this finalized.

**Comment by juniperlsimonis** [comment]
have at it!

**Pull request merged**
