### PR TITLE
Adds naiveArima model to package

### PR DESCRIPTION
**Pull request by skmorgane**
I am victorious! (I think). Followed the instructions for this repo and I think I have added a new model!

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
@skmorgane i've got the NaiveArima fully integrated in #129 
are you ok with closing this PR rather than merging? (or should we merge yours and then the other one?...i think that might cause conflicts, though?)

**Comment by skmorgane** [comment]
I’m totally fine with closing this PR rather than merging it!

**Comment by ethanwhite** [comment]
In cases like this I recommend including a Co-Authored-By line in the relevant commit:
https://stackoverflow.com/questions/7442112/how-to-attribute-a-single-commit-to-multiple-developers

It's an easy way to give credit to the folks contributing even when it's easier not to merge their work in directly.

**Comment by juniperlsimonis** [comment]
totally on board with that. is there a way i can do it retroactively? 
the merge in was mushed in with a few other steps in the process developing the new version, but 9b0ca5c526729913c5cf3b58a759cca002d00e61 is the most relevant commit.
i can also just add something to the PR if that would be easier?/if that's possible?

**Comment by ethanwhite** [comment]
In concept it is possible to do this retroactively using `git rebase -i` but it the ease of doing so depends on how linear the history is and I tried it this morning and it didn't apply cleanly so I think at this point it's not worth the hassle to get it working.

**Pull request closed without merging**
